---
- name: install postgres
  yum:
   name: postgresql-server
   state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: check if PostgreSQL database is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pg_version_exists

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pg_version_exists.stat.exists

- name: start postgres
  service:
    name: postgresql
    state: started
